### ISSUE TITLE
tabs show the last option by default

### ISSUE THREAD

**Issue by julienrf** [scalacenter/docs.scala-lang#12]
Tabs show the last option by default, which is undesirable when we write about Scala CLI, sbt and Mill:

![image](https://user-images.githubusercontent.com/332812/201879011-bf5e0bad-8e98-4b49-ac21-a6d99ad565d9.png)

Instead, we should display the first tab by default.

**Comment by bishabosha** [comment]
for now you can write `defaultTab` in one of the tabs

**Comment by bishabosha** [comment]
but I think the only place where last as default is most desired is the install tabs - so one place
