### ISSUE TITLE
URL of testing tutorials should contain “test” instead of “munit”

### ISSUE THREAD

**Issue by julienrf** [scalacenter/docs.scala-lang#13]
Currently, the URLs of the testing tutorials all contain “munit”. I suggest using a URL with a more general word that relates to the problem rather than the solution:

~~~ text
# currently
https://docs.scala-lang.org/toolkit/munit-assertions.html
# suggestions
https://docs.scala-lang.org/toolkit/testing-assertions.html
https://docs.scala-lang.org/toolkit/test-assertions.html
~~~

**Comment by julienrf** [comment]
I would rather keep the URL and update the content.

**Comment by SethTisue** [comment]
agree this should happen before launch (but also, not a big deal)

**Comment by adpi2** [comment]
I applied the following scheme:
`testing` instead of `munit`
`os` instead of `oslib`
`json` instead of `upickle`
`http-client` instead of `sttp`
